// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDODReLzKqWhb11qs0x7dHY1u_aPBdOdmk',
    appId: '1:937634987762:web:2dc1ecf5889d54363a9a6b',
    messagingSenderId: '937634987762',
    projectId: 'untitled4-11351',
    authDomain: 'untitled4-11351.firebaseapp.com',
    storageBucket: 'untitled4-11351.appspot.com',
    measurementId: 'G-FDDL67ND0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfue9Qb6uUCcfMsUmfNPWwm4xn_JaWmW8',
    appId: '1:937634987762:android:0aae210726c69db43a9a6b',
    messagingSenderId: '937634987762',
    projectId: 'untitled4-11351',
    storageBucket: 'untitled4-11351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAiHoJyaparvO6HZjiJkwWrGl_MtJZias',
    appId: '1:937634987762:ios:79bf7511dbedf5293a9a6b',
    messagingSenderId: '937634987762',
    projectId: 'untitled4-11351',
    storageBucket: 'untitled4-11351.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAiHoJyaparvO6HZjiJkwWrGl_MtJZias',
    appId: '1:937634987762:ios:79bf7511dbedf5293a9a6b',
    messagingSenderId: '937634987762',
    projectId: 'untitled4-11351',
    storageBucket: 'untitled4-11351.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDODReLzKqWhb11qs0x7dHY1u_aPBdOdmk',
    appId: '1:937634987762:web:22396e28241eac3a3a9a6b',
    messagingSenderId: '937634987762',
    projectId: 'untitled4-11351',
    authDomain: 'untitled4-11351.firebaseapp.com',
    storageBucket: 'untitled4-11351.appspot.com',
    measurementId: 'G-EC05L285BV',
  );
}
